### PR TITLE
strip escaped HTML in UI

### PR DESCRIPTION
**Pull request by zbtirrell**
See: https://central.tri.be/issues/62821

Fix this issue:
screenshot 2016-06-23 09 41 02

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [tribe-columns.class.php:149](https://github.com/moderntribe/advanced-post-manager/blob/2241029c06dc3eab47d9828209efd546ea0ae64d/lib/tribe-columns.class.php#L149)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [tribe-columns.class.php:167](https://github.com/moderntribe/advanced-post-manager/blob/2241029c06dc3eab47d9828209efd546ea0ae64d/lib/tribe-columns.class.php#L167)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
I gotta agree with tr1b0t here, we should really be escaping the output of `wp_strip_all_tags()` (because otherwise special symbols that are not part of well formed tags will make it through unescaped).

**Comment by zbtirrell** [comment]
Can you give me an example, I'm not disagreeing, just not sure I follow.

**Comment by barryhughes** [comment]
Sure - pieces of text like `Column -> SubHeading` or `Legit <script` will get through without those angle brackets being converted to the appropriate HTML entity.

**Comment by barryhughes** [comment]
Suave :womans_hat:

**Pull request merged**
